Update .profile

diff --git a/dot_profile.tmpl b/dot_profile.tmpl
--- a/dot_profile.tmpl
+++ b/dot_profile.tmpl
@@ -21,105 +21,103 @@ export MANPAGER='nvim +Man!'
 
 # {{- if eq .chezmoi.os "darwin" }}
 if command -v xcrun >/dev/null 2>&1; then
-    SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
-    export SDKROOT
+  SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
+  export SDKROOT
 fi
 # {{- end }}
 
 if [ -x /home/linuxbrew/.linuxbrew/bin/brew ]; then
-    # shellcheck disable=SC2312
-    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
+  # shellcheck disable=SC2312
+  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
 elif [ -x "${HOME}/.linuxbrew/bin/brew" ]; then
-    # shellcheck disable=SC2312
-    eval "$("${HOME}/.linuxbrew/bin/brew" shellenv)"
+  # shellcheck disable=SC2312
+  eval "$("${HOME}/.linuxbrew/bin/brew" shellenv)"
 fi
 
 #==============================================================#
 ##  PATH                                                      ##
 #==============================================================#
 
-
 export PATH=":${PATH}:/usr/sbin:/sbin"
-
 
 # {{- if eq .chezmoi.os "darwin" }}
 if [ -d "/opt/homebrew/opt/coreutils/libexec/gnubin" ]; then
-    export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:${PATH}"
+  export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:${PATH}"
 fi
 
 if [ -d "/usr/local/opt/coreutils/libexec/gnubin" ]; then
-    export PATH="/usr/local/opt/coreutils/libexec/gnubin:${PATH}"
+  export PATH="/usr/local/opt/coreutils/libexec/gnubin:${PATH}"
 fi
 
 if [ -d "/opt/homebrew/bin" ]; then
-    export PATH="/opt/homebrew/bin:${PATH}"
+  export PATH="/opt/homebrew/bin:${PATH}"
 fi
 
 if [ -d "/opt/homebrew/sbin" ]; then
-    export PATH="/opt/homebrew/sbin:${PATH}"
+  export PATH="/opt/homebrew/sbin:${PATH}"
 fi
 # {{- end }}
 
 if [ -d "${HOME}/.deno/bin" ]; then
-    export DENO_INSTALL="${HOME}/.deno"
-    export PATH="${DENO_INSTALL}/bin:${PATH}"
+  export DENO_INSTALL="${HOME}/.deno"
+  export PATH="${DENO_INSTALL}/bin:${PATH}"
 fi
 
 if [ -d "/opt/homebrew/opt/dotnet@8/libexec" ]; then
-    export DOTNET_ROOT="/opt/homebrew/opt/dotnet@8/libexec"
+  export DOTNET_ROOT="/opt/homebrew/opt/dotnet@8/libexec"
 fi
 
 if [ -d "/opt/homebrew/opt/dotnet@8/bin" ]; then
-    export PATH="/opt/homebrew/opt/dotnet@8/bin:${PATH}"
+  export PATH="/opt/homebrew/opt/dotnet@8/bin:${PATH}"
 fi
 
 if [ -d "${HOME}/.dotnet/tools" ]; then
-    export PATH="${HOME}/.dotnet/tools:${PATH}"
+  export PATH="${HOME}/.dotnet/tools:${PATH}"
 fi
 
 if [ -d "${HOME}/.cargo/bin" ]; then
-    export PATH="${HOME}/.cargo/bin:${PATH}"
+  export PATH="${HOME}/.cargo/bin:${PATH}"
 fi
 
 if [ -d "${HOME}/.nvm" ]; then
-    export NVM_DIR="${HOME}/.nvm"
+  export NVM_DIR="${HOME}/.nvm"
+  # shellcheck disable=SC1091
+  . "${NVM_DIR}/nvm.sh"
+  if [ -d "${NVM_DIR}/bash_completion" ]; then
     # shellcheck disable=SC1091
-    . "${NVM_DIR}/nvm.sh"
-    if [ -d "${NVM_DIR}/bash_completion" ]; then
-        # shellcheck disable=SC1091
-        . "${NVM_DIR}/bash_completion"
-    fi
+    . "${NVM_DIR}/bash_completion"
+  fi
 fi
 
 if [ -d "${HOME}/.rbenv" ]; then
-    export PATH="${HOME}/.rbenv/bin:${PATH}"
-    export PATH="${HOME}/.rbenv/shims:${PATH}"
+  export PATH="${HOME}/.rbenv/bin:${PATH}"
+  export PATH="${HOME}/.rbenv/shims:${PATH}"
 fi
 
 if [ -d "${HOME}/go/bin" ]; then
-    export PATH="${HOME}/go/bin:${PATH}"
+  export PATH="${HOME}/go/bin:${PATH}"
 fi
 
 if [ -d "${HOME}/.pyenv" ]; then
-    export PYENV_ROOT="${HOME}/.pyenv"
-    export PATH="${PYENV_ROOT}/bin:${PATH}"
-    eval "$(pyenv init --path)" || true
+  export PYENV_ROOT="${HOME}/.pyenv"
+  export PATH="${PYENV_ROOT}/bin:${PATH}"
+  eval "$(pyenv init --path)" || true
 fi
 
 if [ -d "${HOME}/bin" ]; then
-    export PATH="${HOME}/bin:${PATH}"
+  export PATH="${HOME}/bin:${PATH}"
 fi
 
 if [ -d "${HOME}/.local/bin" ]; then
-    export PATH="${HOME}/.local/bin:${PATH}"
+  export PATH="${HOME}/.local/bin:${PATH}"
 fi
 
 if [ -d "${HOME}/.nix-profile/bin" ]; then
-    export PATH="${HOME}/.nix-profile/bin:${PATH}"
+  export PATH="${HOME}/.nix-profile/bin:${PATH}"
 fi
 
 if [ -d "${HOME}/Library/Application Support/Coursier/bin" ]; then
-    export PATH="${HOME}/Library/Application Support/Coursier/bin:${PATH}"
+  export PATH="${HOME}/Library/Application Support/Coursier/bin:${PATH}"
 fi
 
 #==============================================================#
@@ -127,45 +125,45 @@ fi
 #==============================================================#
 
 ask() {
-    while true; do
-        printf '%s [y/n] ' "${1}"
-        read -r reply </dev/stdin
-        # Check if the reply is valid
-        case "${reply}" in
-        Y* | y*) return 0 ;;
-        N* | n*) return 1 ;;
-        *) echo 'Please answer yes or no.' ;;
-        esac
-    done
+  while true; do
+    printf '%s [y/n] ' "${1}"
+    read -r reply </dev/stdin
+    # Check if the reply is valid
+    case "${reply}" in
+    Y* | y*) return 0 ;;
+    N* | n*) return 1 ;;
+    *) echo 'Please answer yes or no.' ;;
+    esac
+  done
 }
 
 work() {
-    (cd "${WORKSPACE_DIR}"/"$1" && nvim)
+  (cd "${WORKSPACE_DIR}"/"$1" && nvim)
 }
 
 dotfiles() {
-    (cd "$(chezmoi source-path)" && nvim "$@") || true
+  (cd "$(chezmoi source-path)" && nvim "$@") || true
 }
 
 extract() {
-    case $1 in
-    *.tar.gz | *.tgz) tar xzvf "$1" ;;
-    *.tar.xz) tar Jxvf "$1" ;;
-    *.zip) unzip "$1" ;;
-    *.lzh) lha e "$1" ;;
-    *.tar.bz2 | *.tbz) tar xjvf "$1" ;;
-    *.tar.Z) tar zxvf "$1" ;;
-    *.gz) gzip -d "$1" ;;
-    *.bz2) bzip2 -dc "$1" ;;
-    *.Z) uncompress "$1" ;;
-    *.tar) tar xvf "$1" ;;
-    *.arj) unarj "$1" ;;
-    *) echo "'$1' cannot be extracted via extract()" ;;
-    esac
+  case $1 in
+  *.tar.gz | *.tgz) tar xzvf "$1" ;;
+  *.tar.xz) tar Jxvf "$1" ;;
+  *.zip) unzip "$1" ;;
+  *.lzh) lha e "$1" ;;
+  *.tar.bz2 | *.tbz) tar xjvf "$1" ;;
+  *.tar.Z) tar zxvf "$1" ;;
+  *.gz) gzip -d "$1" ;;
+  *.bz2) bzip2 -dc "$1" ;;
+  *.Z) uncompress "$1" ;;
+  *.tar) tar xvf "$1" ;;
+  *.arj) unarj "$1" ;;
+  *) echo "'$1' cannot be extracted via extract()" ;;
+  esac
 }
 
 randstr() {
-    LC_ALL=C tr -dc 'a-zA-Z0-9' </dev/urandom | fold -w "${1:-32}" | head -n 1
+  LC_ALL=C tr -dc 'a-zA-Z0-9' </dev/urandom | fold -w "${1:-32}" | head -n 1
 }
 
 #==============================================================#
@@ -200,15 +198,15 @@ alias nowdate='date +"%d-%m-%Y"'
 #==============================================================#
 
 if [ -f "${HOME}/.profile.local" ]; then
-    # shellcheck disable=SC1091
-    . "${HOME}/.profile.local"
+  # shellcheck disable=SC1091
+  . "${HOME}/.profile.local"
 fi
 
 if [ -f "${HOME}/.profile.d" ]; then
-    for file in "${HOME}/.profile.d/"*.sh; do
-        if [ -f "${file}" ]; then
-            # shellcheck disable=SC1090
-            . "${file}"
-        fi
-    done
+  for file in "${HOME}/.profile.d/"*.sh; do
+    if [ -f "${file}" ]; then
+      # shellcheck disable=SC1090
+      . "${file}"
+    fi
+  done
 fi
